# Generated by Django 4.1.2 on 2022-10-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=20)),
                ('timeStamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
